server:
  port: 8087
  servlet:
    context-path: /v1/
spring:
  profiles:
    active: dev

## 该配置节点为独立的节点
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.fengchao.workorders.model  # 注意：对应实体类的路径

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql


GAT_NOTIFY_URL: refund/notify
