spring:
  datasource:
     url: jdbc:mysql://122.112.211.218:33143/work_orders?characterEncoding=utf8&useSSL=false&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&serverTimezone=GMT%2B8
     username: fengchao
     password: Smartautotech@123
     driver-class-name: com.mysql.jdbc.Driver

  #Redis
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10000
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

logging:
  file: logs/advertStatistics.log
  pattern:
    file: '%d %-5level [%thread] %logger : %msg%n'
  level:
    org.springframework.web: debug
    com.fengchao.advertising.controller: debug
    com.fengchao.advertising.mapper: debug
    org.hibernate: debug

#腾讯云信分配的账号
AppkeyTXAPP_ID: 1400173080
#腾讯云信分配的密钥
AppSecretTXAPP_KEY: aeaca3d72e0e28a2c1d80fa5011cdf8d
#腾讯云验证码有效期
ActiveTime: 5
#腾讯云模板登录验证码ID template
TemplateID1: 257540
#腾讯云模板更新密码ID template
TemplateID2: 257544
