spring:
  datasource:
     url: jdbc:mysql://127.0.0.1:3306/work_orders?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
     username: guest01
     password: 123qwe
     driver-class-name: com.mysql.cj.jdbc.Driver

