spring:
  datasource:
     url: jdbc:mysql://127.0.0.1:3306/work_orders?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&serverTimezone=GMT%2B8
     username: guest01
     password: 123qwe
     driver-class-name: com.mysql.jdbc.Driver

#GuangAiTong
GAT_NOTIFY_URL: http://xcx-dev.weesharing.com/v2/workorders/refund/notify
GAT_I_APP_ID: '10'

refund:
  ids[0]:
    iAppId: "10"
    apiType: "10"

  ids[1]:
    iAppId: "11"
    apiType: "11"

  ids[2]:
    iAppId: "01"
    apiType: "11"

  ids[3]:
    iAppId: "12"
    apiType: "11"
  ids[4]:
    iAppId: "02"
    apiType: "11"
